Feature: Homepage

@javascript
Scenario: Login
When I visit home page
Then I should see "Paneer"
When I follow "Log in"
Then I should see "Email"
Then I should see "Password"
Then I fill in "session_email" with "chef-0@example.com"
Then I fill in "session_password" with "testpassword"
Then I press "Log in"
Then I should see "You have successfully logged in"
Then I should see "Chef chef 0's profile"


@javascript
Scenario: NonLoggedInUser
When I visit home page
Then I should see "Paneer"
Then I should see "Curry"
When I follow "Chefs"
Then I should see "Chef 0"
Then I should see "Chef 1"
Then I should not see "Delete this chef"
When I follow "Chef 0"
Then I should see "Chef chef 0's profile"
Then I should see "Chef 0's recipes"
Then I should see "Recipe 0"
Then I should see "Recipe 1"
Then I should see "Recipe 2"
Then I should see "Recipe 3"
Then I should see "Recipe 4"
When I follow "Next →"
Then I should see "Recipe 5"
When I follow "Recipe 5"
Then I should see "Recipe 5"
Then I should see "Steps"
Then I should not see "Enter comments"
When I click ".glyphicon-thumbs-up"
Then I should see "You must be logged in to perform that action"
Then I should see "Prior Comments:"
When I follow "All Recipes"
Then I should see "Recipe 0"
Then I should see "Recipe 1"
Then I follow "Recipe 2"
Then I should not see "Edit this recipe"
Then I should not see "Delete this recipe"
Then I should see "ingredient_ 1"
Then I should not see "ingredient_ 10"


@javascript
Scenario: SignUp
When I visit home page
Then I should see "Paneer"
Then I should see "Curry"
When I follow "Sign up for the app"
Then I should see "Enter Chefname"
Then I should see "Email"
Then I should see "Password"
Then I fill in "chef_chefname" with "Cucumber User"
Then I fill in "chef_email" with "cucumber2506-06@test.com"
Then I fill in "chef_password" with "password"
Then I fill in "chef_password_confirmation" with "password"
Then I press "Create my account"
Then I should see "Welcome Cucumber User to MyRecipes App!"
Then I should see "Chef cucumber user's profile"
Then I should see "No recipes yet!"
When I follow "Create recipe"
Then I should see "Name"
Then I should see "Description"
Then I fill in "recipe_name" with "Test Recipe 1"
Then I fill in "recipe_description" with "Creating Recipe, Description, Cucumber Testing"
Then I check "recipe_ingredient_ids_0"
Then I check "recipe_ingredient_ids_5"
Then I check "recipe_ingredient_ids_8"
Then I check "recipe_ingredient_ids_9"
Then I check "recipe_ingredient_ids_10"
Then I press "Create Recipe"
Then I should see "Recipe was created successfully"
Then I should see "Test recipe 1"
Then I should see "Creating Recipe, Description, Cucumber Testing"
Then I should see "Edit this recipe"
Then I should see "Delete this recipe"
Then I should see "Return to recipes listing"
Then I should see "Comment"
When I follow "Edit this recipe"
Then I should see "Edit an existing recipe"
Then I should see "Name"
Then I should see "Description"
Then I fill in "recipe_name" with "Test Recipe 1 edited"
Then I fill in "recipe_description" with "Creating Recipe, Description, Cucumber Testing, Editing this"
Then I press "Update Recipe"
Then I should see "Recipe was updated successfully!"
Then I should see "Test recipe 1 edited"
Then I should see "Creating Recipe, Description, Cucumber Testing, Editing this"
When I follow "Chefs"
Then I should see "Chef 0"
Then I should see "Chef 1"
When I follow "Chef 0"
Then I should see "Chef chef 0's profile"
Then I should see "Chef 0's recipes"
Then I should see "Recipe 0"
Then I should see "Recipe 1"
When I follow "Recipe 1"
Then I should not see "Edit this recipe"
Then I should not see "Delete this recipe"
When I click ".glyphicon-thumbs-up"
Then I should see "Your selection was succesful"
Then I should see "Recipe 1"
When I click ".glyphicon-thumbs-down"
Then I should see "You can only like/dislike a recipe once"
Then I should see "Recipe 1"
When I click ".glyphicon-thumbs-up"
Then I should see "You can only like/dislike a recipe once"
Then I should see "Recipe 1"
When I fill in "comment_description" with "Nice Recipe! I love this."
Then I press "Submit Comment"
Then I should see "Comment was created successfully"
Then I should see "Recipe 1"
Then I should see "Nice Recipe! I love this."


@javascript
Scenario: Admin
When I visit home page
Then I should see "Paneer"
Then I should see "Curry"
When I follow "Log in"
Then I should see "Email"
Then I should see "Password"
Then I fill in "session_email" with "chef-10@example.com"
Then I fill in "session_password" with "testpassword"
Then I press "Log in"
Then I should see "You have successfully logged in"
Then I should see "Chef chef 10's profile"
Then I should see "Recipe 61"
Then I should see "Recipe 62"
When I follow "Ingredients"
Then I should see "New Ingredient"
When I follow "New Ingredient"
Then I should see "Enter a new ingredient"
Then I should see "Name"
When I fill in "ingredient_name" with "ingredient_ 0"
Then I press "Add Ingredient"
Then I should see "Name has already been taken"
Then I should see "Enter a new ingredient"
When I fill in "ingredient_name" with "New ingredient 3"
Then I press "Add Ingredient"
Then I should see "Ingredient was successfully created"
Then I should see "New ingredient 3"
Then I should see "No recipes yet!"